"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00232 import RuleDDF00232
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00232:
    def test_metadata(self):
        rule = RuleDDF00232()
        assert rule._rule == "DDF00232"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == 'An observational study (including patient registries) is expected to have a study phase decode value of "NOT APPLICABLE".'
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
