"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00013 import RuleDDF00013
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00013:
    def test_metadata(self):
        rule = RuleDDF00013()
        assert rule._rule == "DDF00013"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a biomedical concept property is required then it must also be enabled, while if it is not enabled then it must not be required."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00013()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
