"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00155 import RuleDDF00155
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00155:
    def test_metadata(self):
        rule = RuleDDF00155()
        assert rule._rule == "DDF00155"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "For CDISC codelist references (where the code system is 'http://www.cdisc.org'), the code system version must be a valid CDISC terminology release date in ISO 8601 date format."
        )
