"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00152 import RuleDDF00152
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00152:
    def test_metadata(self):
        rule = RuleDDF00152()
        assert rule._rule == "DDF00152"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An activity must only reference timelines that are specified within the same study design."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
