"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00073 import RuleDDF00073
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00073:
    def test_metadata(self):
        rule = RuleDDF00073()
        assert rule._rule == "DDF00073"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "Only one version of any code system is expected to be used within a study version."
        )
