"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00105 import RuleDDF00105
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00105:
    def test_metadata(self):
        rule = RuleDDF00105()
        assert rule._rule == "DDF00105"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A scheduled activity/decision instance must only reference an epoch that is defined within the same study design as the scheduled activity/decision instance."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
