"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00174 import RuleDDF00174
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00174:
    def test_metadata(self):
        rule = RuleDDF00174()
        assert rule._rule == "DDF00174"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == 'An identified organization is not expected to have more than 1 identifier for the study.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
