"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00038 import RuleDDF00038
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00038:
    def test_metadata(self):
        rule = RuleDDF00038()
        assert rule._rule == "DDF00038"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A scheduled decision instance must refer to a default condition."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00038()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
