"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00186 import RuleDDF00186
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00186:
    def test_metadata(self):
        rule = RuleDDF00186()
        assert rule._rule == "DDF00186"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a strength denominator is specified, it must have a unit."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00186()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
