"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00014 import RuleDDF00014
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00014:
    def test_metadata(self):
        rule = RuleDDF00014()
        assert rule._rule == "DDF00014"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "A biomedical concept category is expected to have at least a member or a child."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00014()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
