"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00019 import RuleDDF00019
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00019:
    def test_metadata(self):
        rule = RuleDDF00019()
        assert rule._rule == "DDF00019"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A scheduled activity/decision instance must not refer to itself as its default condition."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00019()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
