"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

from usdm4.rules.library.rule_ddf00153 import RuleDDF00153
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00153:
    def test_metadata(self):
        rule = RuleDDF00153()
        assert rule._rule == "DDF00153"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text == "A planned duration is expected for the main timeline."
        )
