"""Generated by tools/generate_rule_python.py — classification: STUB (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00250 import RuleDDF00250
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00250:
    def test_metadata(self):
        rule = RuleDDF00250()
        assert rule._rule == "DDF00250"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "An eligibility criterion must be referenced by either a study design population or cohorts, not both."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
