"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00082 import RuleDDF00082
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00082:
    def test_metadata(self):
        rule = RuleDDF00082()
        assert rule._rule == "DDF00082"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Data types of attributes (string, number, boolean) must conform with the USDM schema based on the API specification."
        )
