"""Generated by tools/generate_rule_python.py — classification: STUB"""

import pytest
from usdm4.rules.library.rule_ddf00162 import RuleDDF00162
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00162:
    def test_metadata(self):
        rule = RuleDDF00162()
        assert rule._rule == "DDF00162"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "When included in text, references to items stored elsewhere in the data model must be specified in the correct format. They must start with '<usdm:ref', end with either '/>' or '></usdm:ref>', and must contain 'klass=\"KlassName\"',  'id=\"idValue\"', and 'attribute=\"attributeName\"/>' in any order (where \"KlassName\" and \"attributeName\" contain only letters in upper or lower case)."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00162()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
