"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00106 import RuleDDF00106
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00106:
    def test_metadata(self):
        rule = RuleDDF00106()
        assert rule._rule == "DDF00106"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A scheduled activity instance must only reference an encounter that is defined within the same study design as the scheduled activity instance."
        )
