"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00176 import RuleDDF00176
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00176:
    def test_metadata(self):
        rule = RuleDDF00176()
        assert rule._rule == "DDF00176"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An administration's route must be specified according to the extensible Route of Administration Response (C66729) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
