"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00017 import RuleDDF00017
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00017:
    def test_metadata(self):
        rule = RuleDDF00017()
        assert rule._rule == "DDF00017"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Within subject enrollment, the quantity must be a number or a percentage (i.e. the unit must be empty or %)."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00017()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
