"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00185 import RuleDDF00185
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00185:
    def test_metadata(self):
        rule = RuleDDF00185()
        assert rule._rule == "DDF00185"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a dose is specified, then a corresponding administrable product must also be specified either directly or embedded in the medical device and vice versa."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00185()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
