"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

from usdm4.rules.library.rule_ddf00154 import RuleDDF00154
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00154:
    def test_metadata(self):
        rule = RuleDDF00154()
        assert rule._rule == "DDF00154"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'A study design must not be characterized as both "Single-Centre" and "Multicentre".'
        )
