"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00204 import RuleDDF00204
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00204:
    def test_metadata(self):
        rule = RuleDDF00204()
        assert rule._rule == "DDF00204"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Narrative content must only reference narrative content that is specified within the same study definition document version."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
