"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00146 import RuleDDF00146
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00146:
    def test_metadata(self):
        rule = RuleDDF00146()
        assert rule._rule == "DDF00146"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study title type must be specified using the study title type (C207419) DDF codelist."
        )
