"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00254 import RuleDDF00254
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00254:
    def test_metadata(self):
        rule = RuleDDF00254()
        assert rule._rule == "DDF00254"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An activity must only reference child activities that are specified within the same study design."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
