"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00208 import RuleDDF00208
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00208:
    def test_metadata(self):
        rule = RuleDDF00208()
        assert rule._rule == "DDF00208"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An administrable product sourcing must be specified using the extensible administrable product sourcing (C215483) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
