"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00249 import RuleDDF00249
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00249:
    def test_metadata(self):
        rule = RuleDDF00249()
        assert rule._rule == "DDF00249"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "An eligibility criterion item is expected to be used in at least one study design."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
