"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00115 import RuleDDF00115
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00115:
    def test_metadata(self):
        rule = RuleDDF00115()
        assert rule._rule == "DDF00115"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'Every study version must have a title of type "Official Study Title".'

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00115()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
