"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

import pytest
from usdm4.rules.library.rule_ddf00090 import RuleDDF00090
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00090:
    def test_metadata(self):
        rule = RuleDDF00090()
        assert rule._rule == "DDF00090"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "The same Biomedical Concept Category must not be referenced more than once from the same activity."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
