"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00158 import RuleDDF00158
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00158:
    def test_metadata(self):
        rule = RuleDDF00158()
        assert rule._rule == "DDF00158"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Each defined eligibility criterion must be used by at least one study population or cohort within the same study design."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00158()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
