"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00240 import RuleDDF00240
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00240:
    def test_metadata(self):
        rule = RuleDDF00240()
        assert rule._rule == "DDF00240"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A procedure must only reference a study intervention that is referenced by the same study design as the activity within which the procedure is defined."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
