"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00006 import RuleDDF00006
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00006:
    def test_metadata(self):
        rule = RuleDDF00006()
        assert rule._rule == "DDF00006"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Timing windows must be fully defined, if one of the window attributes (i.e., window label, window lower, and window upper) is defined then all must be specified."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
