"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00187 import RuleDDF00187
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00187:
    def test_metadata(self):
        rule = RuleDDF00187()
        assert rule._rule == "DDF00187"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "Narrative content item text is expected to be HTML formatted."
        )
