"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00195 import RuleDDF00195
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00195:
    def test_metadata(self):
        rule = RuleDDF00195()
        assert rule._rule == "DDF00195"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Each study enrollment must apply to either a geographic scope, a study site, or a study cohort."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00195()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
