"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00163 import RuleDDF00163
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00163:
    def test_metadata(self):
        rule = RuleDDF00163()
        assert rule._rule == "DDF00163"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == 'Narrative content is expected to point to a child and/or to a content item text.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
