"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00044 import RuleDDF00044
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00044:
    def test_metadata(self):
        rule = RuleDDF00044()
        assert rule._rule == "DDF00044"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "The target for a condition must not be equal to its parent."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00044()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
