"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00051 import RuleDDF00051
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00051:
    def test_metadata(self):
        rule = RuleDDF00051()
        assert rule._rule == "DDF00051"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A timing's type must be specified using the Timing Type Value Set Terminology (C201264) DDF codelist."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
