"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00023 import RuleDDF00023
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00023:
    def test_metadata(self):
        rule = RuleDDF00023()
        assert rule._rule == "DDF00023"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "To ensure consistent ordering, when both previous and next attributes are available within an entity the previous id value must match the next id value of the referred instance."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
