"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00233 import RuleDDF00233
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00233:
    def test_metadata(self):
        rule = RuleDDF00233()
        assert rule._rule == "DDF00233"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A unit must be coded according to the extensible unit (C71620) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
