"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00101 import RuleDDF00101
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00101:
    def test_metadata(self):
        rule = RuleDDF00101()
        assert rule._rule == "DDF00101"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "Within a study design, if study type is Interventional then at least one intervention is expected to be referenced from a procedure."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00101()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
