"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00241 import RuleDDF00241
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00241:
    def test_metadata(self):
        rule = RuleDDF00241()
        assert rule._rule == "DDF00241"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If the unit is the same (or missing) for both the minimum and maximum value, then the minimum value must be less than the maximum value."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00241()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
