"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00151 import RuleDDF00151
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00151:
    def test_metadata(self):
        rule = RuleDDF00151()
        assert rule._rule == "DDF00151"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "If geographic scope type is global then there must be only one geographic scope specified."
        )
