"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00222 import RuleDDF00222
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00222:
    def test_metadata(self):
        rule = RuleDDF00222()
        assert rule._rule == "DDF00222"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study design, if more intent types are defined, they must be distinct."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
