"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00167 import RuleDDF00167
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00167:
    def test_metadata(self):
        rule = RuleDDF00167()
        assert rule._rule == "DDF00167"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A study definition document version must not be referenced more than once by the same study version."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
