"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00114 import RuleDDF00114
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00114:
    def test_metadata(self):
        rule = RuleDDF00114()
        assert rule._rule == "DDF00114"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "If specified, the context of a condition must point to a valid instance in the activity or scheduled activity instance class."
        )
