"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00168 import RuleDDF00168
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00168:
    def test_metadata(self):
        rule = RuleDDF00168()
        assert rule._rule == "DDF00168"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A piece of narrative content must only reference narrative content items that have been defined within the study version as the narrative content."
        )
