"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

import pytest
from usdm4.rules.library.rule_ddf00052 import RuleDDF00052
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00052:
    def test_metadata(self):
        rule = RuleDDF00052()
        assert rule._rule == "DDF00052"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "All standard code aliases referenced by an instance of the alias code class must be unique."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
