"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00212 import RuleDDF00212
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00212:
    def test_metadata(self):
        rule = RuleDDF00212()
        assert rule._rule == "DDF00212"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "If 'appliesTo' is specified for a product organization role, then the product organization role must only apply to medical devices or administrable products."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
