"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00088 import RuleDDF00088
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00088:
    def test_metadata(self):
        rule = RuleDDF00088()
        assert rule._rule == "DDF00088"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "Epoch ordering using previous and next attributes is expected to be consistent with the order of corresponding scheduled activity instances according to their specified default conditions."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00088()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
