"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

from usdm4.rules.library.rule_ddf00059 import RuleDDF00059
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00059:
    def test_metadata(self):
        rule = RuleDDF00059()
        assert rule._rule == "DDF00059"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study intervention, if more intervention codes are defined, they must be distinct."
        )
