"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00256 import RuleDDF00256
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00256:
    def test_metadata(self):
        rule = RuleDDF00256()
        assert rule._rule == "DDF00256"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "The same reason is not expected to be given as a primary and secondary reason."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00256()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
