"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00040 import RuleDDF00040
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00040:
    def test_metadata(self):
        rule = RuleDDF00040()
        assert rule._rule == "DDF00040"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Each study element must be referenced by at least one study cell."
        )
