"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00011 import RuleDDF00011
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00011:
    def test_metadata(self):
        rule = RuleDDF00011()
        assert rule._rule == "DDF00011"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'Anchor timings (e.g. type is "Fixed Reference") must be related to a scheduled activity instance via a relativeFromScheduledInstance relationship.'
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
