"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00083 import RuleDDF00083
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00083:
    def test_metadata(self):
        rule = RuleDDF00083()
        assert rule._rule == "DDF00083"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text == "Within a study version, all id values must be unique."
        )
