"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00107 import RuleDDF00107
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00107:
    def test_metadata(self):
        rule = RuleDDF00107()
        assert rule._rule == "DDF00107"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'A scheduled activity instance must only have a sub-timeline that is defined within the same study design as the scheduled activity instance.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
