"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00098 import RuleDDF00098
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00098:
    def test_metadata(self):
        rule = RuleDDF00098()
        assert rule._rule == "DDF00098"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study design, the planned sex must be specified either in the study population or in all cohorts."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
