"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (delegated to DDF00082)"""

from usdm4.rules.library.rule_ddf00125 import RuleDDF00125
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00125:
    def test_metadata(self):
        rule = RuleDDF00125()
        assert rule._rule == "DDF00125"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Attributes must be included as defined in the USDM schema based on the API specification (i.e., all required properties are present and no additional attributes are present)."
        )

    def test_validate_is_noop(self):
        """This rule delegates to DDF00082's schema validation. validate() always passes."""
        rule = RuleDDF00125()
        assert rule.validate({"data": None, "ct": None}) is True
