"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00173 import RuleDDF00173
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00173:
    def test_metadata(self):
        rule = RuleDDF00173()
        assert rule._rule == "DDF00173"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'Every identifier must be unique within the scope of an identified organization.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
