"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

import pytest
from usdm4.rules.library.rule_ddf00054 import RuleDDF00054
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00054:
    def test_metadata(self):
        rule = RuleDDF00054()
        assert rule._rule == "DDF00054"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Within an encounter there must be no duplicate contact modes."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
