"""Generated by tools/generate_rule_python.py — classification: STUB"""

import pytest
from usdm4.rules.library.rule_ddf00075 import RuleDDF00075
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00075:
    def test_metadata(self):
        rule = RuleDDF00075()
        assert rule._rule == "DDF00075"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "An activity is expected to refer to at least one procedure, biomedical concept, biomedical concept category or biomedical concept surrogate."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00075()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
