"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

import pytest
from usdm4.rules.library.rule_ddf00100 import RuleDDF00100
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00100:
    def test_metadata(self):
        rule = RuleDDF00100()
        assert rule._rule == "DDF00100"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study version, there must be no more than one title of each type."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
