"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00246 import RuleDDF00246
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00246:
    def test_metadata(self):
        rule = RuleDDF00246()
        assert rule._rule == "DDF00246"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'Any parameter name referenced in a tag in the text should be specified in the data dictionary parameter maps.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
