"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00022 import RuleDDF00022
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00022:
    def test_metadata(self):
        rule = RuleDDF00022()
        assert rule._rule == "DDF00022"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An instance of a class must not refer to itself as its next instance."
        )
