"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00046 import RuleDDF00046
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00046:
    def test_metadata(self):
        rule = RuleDDF00046()
        assert rule._rule == "DDF00046"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A timing must only be specified as being relative to/from a scheduled activity/decision instance that is defined within the same timeline as the timing."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00046()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
