"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00228 import RuleDDF00228
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00228:
    def test_metadata(self):
        rule = RuleDDF00228()
        assert rule._rule == "DDF00228"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An observational study (including patient registries) must be specified using the ObservationalStudyDesign class."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
