"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00035 import RuleDDF00035
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00035:
    def test_metadata(self):
        rule = RuleDDF00035()
        assert rule._rule == "DDF00035"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "Within a code system and corresponding version, a one-to-one relationship between code and decode is expected."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
