"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00223 import RuleDDF00223
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00223:
    def test_metadata(self):
        rule = RuleDDF00223()
        assert rule._rule == "DDF00223"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study design's observational model must be specified according to the extensible Observational Study Model (C127259) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
