"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00231 import RuleDDF00231
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00231:
    def test_metadata(self):
        rule = RuleDDF00231()
        assert rule._rule == "DDF00231"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a biospecimen retention indicates that a type of biospecimen is retained, then there must be an indication of whether the type of biospecimen includes DNA."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00231()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
