"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00201 import RuleDDF00201
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00201:
    def test_metadata(self):
        rule = RuleDDF00201()
        assert rule._rule == "DDF00201"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "There must be exactly one study role with a code of sponsor."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00201()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
