"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00161 import RuleDDF00161
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00161:
    def test_metadata(self):
        rule = RuleDDF00161()
        assert rule._rule == "DDF00161"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "The ordering of activities (using the previous and next attributes) must include the parents (e.g. activities referring to children) preceding their children."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00161()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
