"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00239 import RuleDDF00239
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00239:
    def test_metadata(self):
        rule = RuleDDF00239()
        assert rule._rule == "DDF00239"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "If a strength numerator range is specified, both the minValue and maxValue must have a unit."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
