"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00214 import RuleDDF00214
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00214:
    def test_metadata(self):
        rule = RuleDDF00214()
        assert rule._rule == "DDF00214"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An interventional study design's intent types must be specified according to the extensible Trial Intent Type Response (C66736) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
