"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00254 import RuleDDF00254
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00254:
    def test_metadata(self):
        rule = RuleDDF00254()
        assert rule._rule == "DDF00254"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An activity must only reference child activities that are specified within the same study design."
        )
