"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00160 import RuleDDF00160
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00160:
    def test_metadata(self):
        rule = RuleDDF00160()
        assert rule._rule == "DDF00160"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An activity with children must not refer to a timeline, procedure, biomedical concept, biomedical concept category or biomedical concept surrogate."
        )
