"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00096 import RuleDDF00096
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00096:
    def test_metadata(self):
        rule = RuleDDF00096()
        assert rule._rule == "DDF00096"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "All primary endpoints must be referenced by a primary objective."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
