"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00237 import RuleDDF00237
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00237:
    def test_metadata(self):
        rule = RuleDDF00237()
        assert rule._rule == "DDF00237"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "The unit of a planned age is expected to be specified using terms from the Age Unit (C66781) SDTM codelist."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
