"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00241 import RuleDDF00241
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00241:
    def test_metadata(self):
        rule = RuleDDF00241()
        assert rule._rule == "DDF00241"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If the unit is the same (or missing) for both the minimum and maximum value, then the minimum value must be less than the maximum value."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
