"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00192 import RuleDDF00192
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00192:
    def test_metadata(self):
        rule = RuleDDF00192()
        assert rule._rule == "DDF00192"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == 'A masking is expected to be defined for at least two study roles in a study design with a double blind blinding schema.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
