"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

import pytest
from usdm4.rules.library.rule_ddf00027 import RuleDDF00027
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00027:
    def test_metadata(self):
        rule = RuleDDF00027()
        assert rule._rule == "DDF00027"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "To ensure consistent ordering, the same instance must not be referenced more than once as previous or next."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00027()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
