"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00128 import RuleDDF00128
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00128:
    def test_metadata(self):
        rule = RuleDDF00128()
        assert rule._rule == "DDF00128"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study intervention's type must be specified using the Intervention Type Response (C99078) SDTM codelist."
        )
