"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00007 import RuleDDF00007
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00007:
    def test_metadata(self):
        rule = RuleDDF00007()
        assert rule._rule == "DDF00007"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'If timing type is "Fixed Reference" then it must point to only one scheduled instance (e.g. attribute relativeToScheduledInstance must be equal to relativeFromScheduledInstance or it must be missing).'
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
