"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00104 import RuleDDF00104
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00104:
    def test_metadata(self):
        rule = RuleDDF00104()
        assert rule._rule == "DDF00104"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A timing's relative to/from property must be specified using the Timing Relative To From Value Set Terminology (C201265) SDTM codelist."
        )
