"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00243 import RuleDDF00243
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00243:
    def test_metadata(self):
        rule = RuleDDF00243()
        assert rule._rule == "DDF00243"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "Each StudyArm is expected to have one StudyCell for each StudyEpoch."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00243()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
