"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00180 import RuleDDF00180
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00180:
    def test_metadata(self):
        rule = RuleDDF00180()
        assert rule._rule == "DDF00180"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An administrable product property type must be specified according to the extensible administrable property type (C215479) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
