"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00221 import RuleDDF00221
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00221:
    def test_metadata(self):
        rule = RuleDDF00221()
        assert rule._rule == "DDF00221"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Within a study design, if more therapeutic areas are defined, they must be distinct."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00221()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
