"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00080 import RuleDDF00080
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00080:
    def test_metadata(self):
        rule = RuleDDF00080()
        assert rule._rule == "DDF00080"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "All scheduled activity instances are expected to refer to an epoch."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00080()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
