"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00069 import RuleDDF00069
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00069:
    def test_metadata(self):
        rule = RuleDDF00069()
        assert rule._rule == "DDF00069"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Each combination of arm and epoch must occur no more than once within a study design."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
