"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00171 import RuleDDF00171
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00171:
    def test_metadata(self):
        rule = RuleDDF00171()
        assert rule._rule == "DDF00171"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "The expanded text for all abbreviations defined for a study version are expected to be unique."
        )
