"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00203 import RuleDDF00203
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00203:
    def test_metadata(self):
        rule = RuleDDF00203()
        assert rule._rule == "DDF00203"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "The sponsor study role must be applicable to a study version."
        )
