"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00159 import RuleDDF00159
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00159:
    def test_metadata(self):
        rule = RuleDDF00159()
        assert rule._rule == "DDF00159"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An eligibility criterion must not be referenced by both a study design population and any of the cohorts of the same study design population."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
