"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00047 import RuleDDF00047
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00047:
    def test_metadata(self):
        rule = RuleDDF00047()
        assert rule._rule == "DDF00047"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study cell must only reference elements that are defined within the same study design as the study cell."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
