"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00213 import RuleDDF00213
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00213:
    def test_metadata(self):
        rule = RuleDDF00213()
        assert rule._rule == "DDF00213"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "If the intervention model indicates a single group design then only one intervention is expected. In all other cases more interventions are expected."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00213()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
