"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE (hand-authored)"""

from usdm4.rules.library.rule_ddf00093 import RuleDDF00093
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00093:
    def test_metadata(self):
        rule = RuleDDF00093()
        assert rule._rule == "DDF00093"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Date values associated to a study version must be unique regarding the combination of type and geographic scopes of the date."
        )
