"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00039 import RuleDDF00039
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00039:
    def test_metadata(self):
        rule = RuleDDF00039()
        assert rule._rule == "DDF00039"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "If the duration will vary, a quantity is not expected for the duration and vice versa."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
