"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00193 import RuleDDF00193
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00193:
    def test_metadata(self):
        rule = RuleDDF00193()
        assert rule._rule == "DDF00193"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "A masking is expected to be defined for at least one study role in a study design with a blinding schema that is not open label or double blind."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
