"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00172 import RuleDDF00172
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00172:
    def test_metadata(self):
        rule = RuleDDF00172()
        assert rule._rule == "DDF00172"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "There must be exactly one sponsor study identifier (i.e., a study identifier whose scope is an organization that is identified as the organization for the sponsor study role)."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
