"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00033 import RuleDDF00033
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00033:
    def test_metadata(self):
        rule = RuleDDF00033()
        assert rule._rule == "DDF00033"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "At least the text or the quantity must be specified for a duration."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00033()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
