"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00148 import RuleDDF00148
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00148:
    def test_metadata(self):
        rule = RuleDDF00148()
        assert rule._rule == "DDF00148"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "An endpoint level must be specified using the endpoint level (C188726) DDF codelist."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
