"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00141 import RuleDDF00141
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00141:
    def test_metadata(self):
        rule = RuleDDF00141()
        assert rule._rule == "DDF00141"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A planned sex must be specified using the Sex of Participants (C66732) SDTM codelist."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
