"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (hand-authored)"""

from usdm4.rules.library.rule_ddf00028 import RuleDDF00028
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00028:
    def test_metadata(self):
        rule = RuleDDF00028()
        assert rule._rule == "DDF00028"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An activity must only reference activities that are specified within the same study design."
        )
