"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00206 import RuleDDF00206
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00206:
    def test_metadata(self):
        rule = RuleDDF00206()
        assert rule._rule == "DDF00206"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Sourcing must not be defined for an administrable product which is only referenced as an embedded product for a medical device."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
