"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00198 import RuleDDF00198
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00198:
    def test_metadata(self):
        rule = RuleDDF00198()
        assert rule._rule == "DDF00198"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "Each study definition document version is expected to be referenced by either a study version or a study design."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00198()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
