"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00220 import RuleDDF00220
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00220:
    def test_metadata(self):
        rule = RuleDDF00220()
        assert rule._rule == "DDF00220"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study design, if more sub types are defined, they must be distinct."
        )
