"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00164 import RuleDDF00164
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00164:
    def test_metadata(self):
        rule = RuleDDF00164()
        assert rule._rule == "DDF00164"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a section number is to be displayed then a number must be specified and vice versa."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00164()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
