"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00031 import RuleDDF00031
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00031:
    def test_metadata(self):
        rule = RuleDDF00031()
        assert rule._rule == "DDF00031"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'If timing type is not "Fixed Reference" then it must point to two scheduled instances (e.g. the relativeFromScheduledInstance and relativeToScheduledInstance attributes must not be missing and must not be equal to each other).'
        )
