"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00246 import RuleDDF00246
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00246:
    def test_metadata(self):
        rule = RuleDDF00246()
        assert rule._rule == "DDF00246"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Any parameter name referenced in a tag in the text should be specified in the data dictionary parameter maps."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00246()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
