"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00205 import RuleDDF00205
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00205:
    def test_metadata(self):
        rule = RuleDDF00205()
        assert rule._rule == "DDF00205"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An administrable product must not be referenced as both the administrable product for an administration and the embedded product of a medical device that is referenced by the same administration."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
