"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00253 import RuleDDF00253
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00253:
    def test_metadata(self):
        rule = RuleDDF00253()
        assert rule._rule == "DDF00253"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A reference substance must not have a reference substance."
        )
