"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00143 import RuleDDF00143
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00143:
    def test_metadata(self):
        rule = RuleDDF00143()
        assert rule._rule == "DDF00143"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study amendment reason must be coded using the study amendment reason (C207415) DDF codelist."
        )
