"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

import pytest
from usdm4.rules.library.rule_ddf00181 import RuleDDF00181
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00181:
    def test_metadata(self):
        rule = RuleDDF00181()
        assert rule._rule == "DDF00181"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Date values associated to a study protocol document version must be unique regarding the combination of type and geographic scopes of the date."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00181()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
