"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00210 import RuleDDF00210
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00210:
    def test_metadata(self):
        rule = RuleDDF00210()
        assert rule._rule == "DDF00210"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An administrable product's product designation must be specified using the product designation (C207418) DDF codelist."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
