"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00191 import RuleDDF00191
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00191:
    def test_metadata(self):
        rule = RuleDDF00191()
        assert rule._rule == "DDF00191"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "A masking is not expected to be defined for any study role in a study design with an open label blinding schema."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00191()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
