"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00235 import RuleDDF00235
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00235:
    def test_metadata(self):
        rule = RuleDDF00235()
        assert rule._rule == "DDF00235"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A unit must not be specified for a planned completion number."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
