"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00042 import RuleDDF00042
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00042:
    def test_metadata(self):
        rule = RuleDDF00042()
        assert rule._rule == "DDF00042"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "The range specified for a planned age is not expected to be approximate."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
