"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00177 import RuleDDF00177
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00177:
    def test_metadata(self):
        rule = RuleDDF00177()
        assert rule._rule == "DDF00177"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "If an administration's dose is specified then a corresponding route is expected and vice versa."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
