"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00242 import RuleDDF00242
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00242:
    def test_metadata(self):
        rule = RuleDDF00242()
        assert rule._rule == "DDF00242"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "For each range, a unit must be specified either for both the minimum and the maximum value, or for neither of them."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00242()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
