"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00218 import RuleDDF00218
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00218:
    def test_metadata(self):
        rule = RuleDDF00218()
        assert rule._rule == "DDF00218"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study design's characteristics must be specified according to the extensible study design characteristics (C207416) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
