"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00256 import RuleDDF00256
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00256:
    def test_metadata(self):
        rule = RuleDDF00256()
        assert rule._rule == "DDF00256"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "The same reason is not expected to be given as a primary and secondary reason."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
