"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00217 import RuleDDF00217
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00217:
    def test_metadata(self):
        rule = RuleDDF00217()
        assert rule._rule == "DDF00217"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study design's blinding schema must be specified according to the extensible Trial Blinding Schema Response (C66735) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
