"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00257 import RuleDDF00257
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00257:
    def test_metadata(self):
        rule = RuleDDF00257()
        assert rule._rule == "DDF00257"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'A study design must not be characterized as both "Single Country" and "Multiple Countries".'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
