"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00219 import RuleDDF00219
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00219:
    def test_metadata(self):
        rule = RuleDDF00219()
        assert rule._rule == "DDF00219"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Within a study design, if more characteristics are defined, they must be distinct."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00219()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
