"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00110 import RuleDDF00110
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00110:
    def test_metadata(self):
        rule = RuleDDF00110()
        assert rule._rule == "DDF00110"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "An eligibility criterion's category must be specified using the Category of Inclusion/Exclusion (C66797) SDTM codelist."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00110()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
