"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00050 import RuleDDF00050
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00050:
    def test_metadata(self):
        rule = RuleDDF00050()
        assert rule._rule == "DDF00050"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study arm must only reference study populations or cohorts that are defined within the same study design as the study arm."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
