"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00189 import RuleDDF00189
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00189:
    def test_metadata(self):
        rule = RuleDDF00189()
        assert rule._rule == "DDF00189"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Every study role must apply to either a study version or at least one study design, but not both."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00189()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
