"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00010 import RuleDDF00010
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00010:
    def test_metadata(self):
        rule = RuleDDF00010()
        assert rule._rule == "DDF00010"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "The names of all child instances of the same parent class must be unique."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00010()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
