"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

from usdm4.rules.library.rule_ddf00032 import RuleDDF00032
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00032:
    def test_metadata(self):
        rule = RuleDDF00032()
        assert rule._rule == "DDF00032"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study version, if more than 1 business therapeutic area is defined then they must be distinct."
        )
