"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00188 import RuleDDF00188
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00188:
    def test_metadata(self):
        rule = RuleDDF00188()
        assert rule._rule == "DDF00188"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A planned sex must ether include a single entry of male or female or both female and male as entries."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
