"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00144 import RuleDDF00144
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00144:
    def test_metadata(self):
        rule = RuleDDF00144()
        assert rule._rule == "DDF00144"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study geographic scope type must be specified using the geographic scope type (C207412) DDF codelist."
        )
