"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

from usdm4.rules.library.rule_ddf00012 import RuleDDF00012
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00012:
    def test_metadata(self):
        rule = RuleDDF00012()
        assert rule._rule == "DDF00012"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study design, there must be exactly one scheduled timeline which identifies as the main Timeline."
        )
