"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00014 import RuleDDF00014
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00014:
    def test_metadata(self):
        rule = RuleDDF00014()
        assert rule._rule == "DDF00014"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "A biomedical concept category is expected to have at least a member or a child."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
