"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00127 import RuleDDF00127
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00127:
    def test_metadata(self):
        rule = RuleDDF00127()
        assert rule._rule == "DDF00127"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An encounter must only be scheduled at a timing that is defined within the same study design as the encounter."
        )
