"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (delegated to DDF00082)"""

from usdm4.rules.library.rule_ddf00081 import RuleDDF00081
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00081:
    def test_metadata(self):
        rule = RuleDDF00081()
        assert rule._rule == "DDF00081"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Class relationships must conform with the USDM schema based on the API specification."
        )

    def test_validate_is_noop(self):
        """This rule delegates to DDF00082's schema validation. validate() always passes."""
        rule = RuleDDF00081()
        assert rule.validate({"data": None, "ct": None}) is True
