"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00076 import RuleDDF00076
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00076:
    def test_metadata(self):
        rule = RuleDDF00076()
        assert rule._rule == "DDF00076"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "If a biomedical concept is referenced from an activity then it is not expected to be referenced as well by a biomedical concept category that is referenced from the same activity."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00076()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
