"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00209 import RuleDDF00209
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00209:
    def test_metadata(self):
        rule = RuleDDF00209()
        assert rule._rule == "DDF00209"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A medical device sourcing must be specified using the extensible medical device sourcing (C215482) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
