"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00030 import RuleDDF00030
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00030:
    def test_metadata(self):
        rule = RuleDDF00030()
        assert rule._rule == "DDF00030"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "At least the text or the family name must be specified for a person name."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00030()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
