"""Generated by tools/generate_rule_python.py — classification: HIGH_FORMAT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00137 import RuleDDF00137
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00137:
    def test_metadata(self):
        rule = RuleDDF00137()
        assert rule._rule == "DDF00137"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'References must be a fixed value or a reference to items stored elsewhere in the data model which must be specified in the correct format. They must start with \'<usdm:ref\', end with either \'/>\' or \'></usdm:ref>\', and must contain \'klass="klassName"\', \'id="idValue"\', and \'attribute="attributeName"/>\' in any order (where "klassName" and "attributeName" contain only letters in upper or lower case).'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
