"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00017 import RuleDDF00017
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00017:
    def test_metadata(self):
        rule = RuleDDF00017()
        assert rule._rule == "DDF00017"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within subject enrollment, the quantity must be a number or a percentage (i.e. the unit must be empty or %)."
        )
