"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00182 import RuleDDF00182
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00182:
    def test_metadata(self):
        rule = RuleDDF00182()
        assert rule._rule == "DDF00182"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "Within a study protocol document version, if a date of a specific type exists with a global geographic scope then no other dates are expected with the same type."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
