"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00115 import RuleDDF00115
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00115:
    def test_metadata(self):
        rule = RuleDDF00115()
        assert rule._rule == "DDF00115"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'Every study version must have a title of type "Official Study Title".'
        )
