"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00080 import RuleDDF00080
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00080:
    def test_metadata(self):
        rule = RuleDDF00080()
        assert rule._rule == "DDF00080"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "All scheduled activity instances are expected to refer to an epoch."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
