"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00207 import RuleDDF00207
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00207:
    def test_metadata(self):
        rule = RuleDDF00207()
        assert rule._rule == "DDF00207"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A medical device identifier type must be specified according to the extensible medical device identifier type (C215484) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
