"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00178 import RuleDDF00178
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00178:
    def test_metadata(self):
        rule = RuleDDF00178()
        assert rule._rule == "DDF00178"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "If a dose is specified then a corresponding frequency must also be specified."
        )
