"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00247 import RuleDDF00247
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00247:
    def test_metadata(self):
        rule = RuleDDF00247()
        assert rule._rule == "DDF00247"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text == "Syntax template text is expected to be HTML formatted."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
