"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00190 import RuleDDF00190
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00190:
    def test_metadata(self):
        rule = RuleDDF00190()
        assert rule._rule == "DDF00190"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A study role must not reference both assigned persons and organizations."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00190()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
