"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00036 import RuleDDF00036
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00036:
    def test_metadata(self):
        rule = RuleDDF00036()
        assert rule._rule == "DDF00036"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'If timing type is "Fixed Reference" then the corresponding attribute relativeToFrom must be filled with "Start to Start".'
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
