"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00255 import RuleDDF00255
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00255:
    def test_metadata(self):
        rule = RuleDDF00255()
        assert rule._rule == "DDF00255"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "A primary study amendment reason is not expected to be 'not applicable'."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
