"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00018 import RuleDDF00018
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00018:
    def test_metadata(self):
        rule = RuleDDF00018()
        assert rule._rule == "DDF00018"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An instance of a class must not reference itself as one of its own children."
        )
