"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00240 import RuleDDF00240
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00240:
    def test_metadata(self):
        rule = RuleDDF00240()
        assert rule._rule == "DDF00240"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A procedure must only reference a study intervention that is referenced by the same study design as the activity within which the procedure is defined."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00240()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
