"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00211 import RuleDDF00211
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00211:
    def test_metadata(self):
        rule = RuleDDF00211()
        assert rule._rule == "DDF00211"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "A product organization role is expected to apply to at least one medical device or administrable product."
        )
