"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00008 import RuleDDF00008
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00008:
    def test_metadata(self):
        rule = RuleDDF00008()
        assert rule._rule == "DDF00008"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A scheduled activity instance must refer to either a default condition or a timeline exit, but not both."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
