"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00087 import RuleDDF00087
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00087:
    def test_metadata(self):
        rule = RuleDDF00087()
        assert rule._rule == "DDF00087"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "Encounter ordering using previous and next attributes is expected to be consistent with the order of corresponding scheduled activity instances according to their specified default conditions."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
