"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE"""

from usdm4.rules.library.rule_ddf00058 import RuleDDF00058
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00058:
    def test_metadata(self):
        rule = RuleDDF00058()
        assert rule._rule == "DDF00058"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within an indication, if more indication codes are defined, they must be distinct."
        )
