"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00224 import RuleDDF00224
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00224:
    def test_metadata(self):
        rule = RuleDDF00224()
        assert rule._rule == "DDF00224"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An observational study design's time perspective must be specified according to the extensible Observational Study Time Perspective (C127261) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
