"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00063 import RuleDDF00063
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00063:
    def test_metadata(self):
        rule = RuleDDF00063()
        assert rule._rule == "DDF00063"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == "A standard code alias is not expected to be equal to the standard code (e.g. no equal code or decode for the same coding system version is expected)."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
