"""Generated by tools/generate_rule_python.py — classification: STUB (hand-authored)"""

from usdm4.rules.library.rule_ddf00184 import RuleDDF00184
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00184:
    def test_metadata(self):
        rule = RuleDDF00184()
        assert rule._rule == "DDF00184"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A substance must not references itself as a reference substance."
        )
