"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00108 import RuleDDF00108
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00108:
    def test_metadata(self):
        rule = RuleDDF00108()
        assert rule._rule == "DDF00108"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "There must be at least one exit defined for each timeline (i.e., at least one instance of StudyTimelineExit linked via the 'exits' relationship)."
        )
