"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00244 import RuleDDF00244
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00244:
    def test_metadata(self):
        rule = RuleDDF00244()
        assert rule._rule == "DDF00244"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Referenced items in the narrative content item texts must be available elsewhere in the data model."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00244()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
