"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00033 import RuleDDF00033
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00033:
    def test_metadata(self):
        rule = RuleDDF00033()
        assert rule._rule == "DDF00033"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "At least the text or the quantity must be specified for a duration."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
