"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00191 import RuleDDF00191
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00191:
    def test_metadata(self):
        rule = RuleDDF00191()
        assert rule._rule == "DDF00191"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == 'A masking is not expected to be defined for any study role in a study design with an open label blinding schema.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
