"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00252 import RuleDDF00252
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00252:
    def test_metadata(self):
        rule = RuleDDF00252()
        assert rule._rule == "DDF00252"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study element must only reference study interventions that are referenced by the same study design as the study element."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
