"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00133 import RuleDDF00133
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00133:
    def test_metadata(self):
        rule = RuleDDF00133()
        assert rule._rule == "DDF00133"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Within a study design, if a planned enrollment number is defined, it must be specified either in the study population or in all cohorts."
        )
