"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00260 import RuleDDF00260
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00260:
    def test_metadata(self):
        rule = RuleDDF00260()
        assert rule._rule == "DDF00260"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "Id values are expected not to have spaces in their string values."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
