"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00029 import RuleDDF00029
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00029:
    def test_metadata(self):
        rule = RuleDDF00029()
        assert rule._rule == "DDF00029"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "An encounter must only reference encounters that are specified within the same study design."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00029()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
