"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00071 import RuleDDF00071
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00071:
    def test_metadata(self):
        rule = RuleDDF00071()
        assert rule._rule == "DDF00071"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A study cell must only reference an arm that is defined within the same study design as the study cell."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00071()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
