"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00189 import RuleDDF00189
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00189:
    def test_metadata(self):
        rule = RuleDDF00189()
        assert rule._rule == "DDF00189"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Every study role must apply to either a study version or at least one study design, but not both."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
