"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00261 import RuleDDF00261
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00261:
    def test_metadata(self):
        rule = RuleDDF00261()
        assert rule._rule == "DDF00261"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "If a geographic scope type is global then no code is expected to specify the specific area within scope while if it is not global then a code is expected to specify the specific area within scope."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
