"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00227 import RuleDDF00227
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00227:
    def test_metadata(self):
        rule = RuleDDF00227()
        assert rule._rule == "DDF00227"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "An interventional study must be specified using the InterventionalStudyDesign class."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00227()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
