"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (delegated to DDF00082)"""

from usdm4.rules.library.rule_ddf00126 import RuleDDF00126
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00126:
    def test_metadata(self):
        rule = RuleDDF00126()
        assert rule._rule == "DDF00126"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'Cardinalities must be as defined in the USDM schema based on the API specification (i.e., required properties have at least one value and single-value properties are not lists).'

    def test_validate_is_noop(self):
        """This rule delegates to DDF00082's schema validation. validate() always passes."""
        rule = RuleDDF00126()
        assert rule.validate({"data": None, "ct": None}) is True
