"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00034 import RuleDDF00034
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00034:
    def test_metadata(self):
        rule = RuleDDF00034()
        assert rule._rule == "DDF00034"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If duration will vary (attribute durationWillVary is True) then a reason (attribute reasonDurationWillVary) must be given and vice versa."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00034()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
