"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00196 import RuleDDF00196
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00196:
    def test_metadata(self):
        rule = RuleDDF00196()
        assert rule._rule == "DDF00196"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "There must be a one-to-one relationship between referenced section number and title within a study amendment."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00196()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
