"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

from usdm4.rules.library.rule_ddf00213 import RuleDDF00213
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00213:
    def test_metadata(self):
        rule = RuleDDF00213()
        assert rule._rule == "DDF00213"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "If the intervention model indicates a single group design then only one intervention is expected. In all other cases more interventions are expected."
        )
