"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00199 import RuleDDF00199
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00199:
    def test_metadata(self):
        rule = RuleDDF00199()
        assert rule._rule == "DDF00199"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An study impact type must be specified according to the extensible study amendment impact type (C215481) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
