"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00173 import RuleDDF00173
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00173:
    def test_metadata(self):
        rule = RuleDDF00173()
        assert rule._rule == "DDF00173"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Every identifier must be unique within the scope of an identified organization."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00173()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
