"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

from usdm4.rules.library.rule_ddf00150 import RuleDDF00150
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00150:
    def test_metadata(self):
        rule = RuleDDF00150()
        assert rule._rule == "DDF00150"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An encounter type must be specified according to the extensible encounter type (C188728) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
