"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER (hand-authored)"""

from usdm4.rules.library.rule_ddf00024 import RuleDDF00024
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00024:
    def test_metadata(self):
        rule = RuleDDF00024()
        assert rule._rule == "DDF00024"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An epoch must only reference epochs that are specified within the same study design."
        )
