"""Generated by tools/generate_rule_python.py — classification: HIGH_UNIQUE_WITHIN_SCOPE (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00245 import RuleDDF00245
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00245:
    def test_metadata(self):
        rule = RuleDDF00245()
        assert rule._rule == "DDF00245"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'Within a document version, the specified section numbers for narrative content must be unique.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
