"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

from usdm4.rules.library.rule_ddf00202 import RuleDDF00202
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00202:
    def test_metadata(self):
        rule = RuleDDF00202()
        assert rule._rule == "DDF00202"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "The sponsor study role must point to exactly one organization."
        )
