"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00025 import RuleDDF00025
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00025:
    def test_metadata(self):
        rule = RuleDDF00025()
        assert rule._rule == "DDF00025"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == 'A window must not be defined for an anchor timing (i.e., type is "Fixed Reference").'
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
