"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00084 import RuleDDF00084
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00084:
    def test_metadata(self):
        rule = RuleDDF00084()
        assert rule._rule == "DDF00084"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Within a study design there must be exactly one objective with level 'Primary Objective'."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00084()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
