"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00212 import RuleDDF00212
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00212:
    def test_metadata(self):
        rule = RuleDDF00212()
        assert rule._rule == "DDF00212"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If 'appliesTo' is specified for a product organization role, then the product organization role must only apply to medical devices or administrable products."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00212()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
