"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00259 import RuleDDF00259
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00259:
    def test_metadata(self):
        rule = RuleDDF00259()
        assert rule._rule == "DDF00259"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study role code must be specified according to the (C215480) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
