"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00234 import RuleDDF00234
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00234:
    def test_metadata(self):
        rule = RuleDDF00234()
        assert rule._rule == "DDF00234"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A unit must not be specified for a planned enrollment number."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00234()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
