"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00102 import RuleDDF00102
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00102:
    def test_metadata(self):
        rule = RuleDDF00102()
        assert rule._rule == "DDF00102"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A scheduled activity instance must only reference a timeline exit that is defined within the same schedule timeline as the scheduled activity instance."
        )
