"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00179 import RuleDDF00179
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00179:
    def test_metadata(self):
        rule = RuleDDF00179()
        assert rule._rule == "DDF00179"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An administrable dose form must be specified according to the extensible Pharmaceutical Dosage Form (C66726) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
