"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00186 import RuleDDF00186
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00186:
    def test_metadata(self):
        rule = RuleDDF00186()
        assert rule._rule == "DDF00186"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a strength denominator is specified, it must have a unit."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
