"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00166 import RuleDDF00166
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00166:
    def test_metadata(self):
        rule = RuleDDF00166()
        assert rule._rule == "DDF00166"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study definition document type must be specified according to the extensible study definition document type (C215477) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
