"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00206 import RuleDDF00206
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00206:
    def test_metadata(self):
        rule = RuleDDF00206()
        assert rule._rule == "DDF00206"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Sourcing must not be defined for an administrable product which is only referenced as an embedded product for a medical device."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00206()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
