"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00245 import RuleDDF00245
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00245:
    def test_metadata(self):
        rule = RuleDDF00245()
        assert rule._rule == "DDF00245"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Within a document version, the specified section numbers for narrative content must be unique."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00245()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
