"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

from usdm4.rules.library.rule_ddf00021 import RuleDDF00021
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00021:
    def test_metadata(self):
        rule = RuleDDF00021()
        assert rule._rule == "DDF00021"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An instance of a class must not refer to itself as its previous instance."
        )
