"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00009 import RuleDDF00009
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00009:
    def test_metadata(self):
        rule = RuleDDF00009()
        assert rule._rule == "DDF00009"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Each schedule timeline must contain at least one anchor (fixed time) - i.e., at least one scheduled activity instance that is referenced by a Fixed Reference timing."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
