"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00124 import RuleDDF00124
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00124:
    def test_metadata(self):
        rule = RuleDDF00124()
        assert rule._rule == "DDF00124"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "Referenced items in a parameter map must be available elsewhere in the data model."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
