"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00258 import RuleDDF00258
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00258:
    def test_metadata(self):
        rule = RuleDDF00258()
        assert rule._rule == "DDF00258"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == 'A study design is not expected to have more than one of the following characteristics: "Randomized", "Stratification", "Stratified Randomisation".'
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
