"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00165 import RuleDDF00165
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00165:
    def test_metadata(self):
        rule = RuleDDF00165()
        assert rule._rule == "DDF00165"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "If a section title is to be displayed then a title must be specified and vice versa."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00165()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
