"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00010 import RuleDDF00010
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00010:
    def test_metadata(self):
        rule = RuleDDF00010()
        assert rule._rule == "DDF00010"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'The names of all child instances of the same parent class must be unique.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
