"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

from usdm4.rules.library.rule_ddf00248 import RuleDDF00248
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00248:
    def test_metadata(self):
        rule = RuleDDF00248()
        assert rule._rule == "DDF00248"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An eligibility criterion item must not be used more than once within a study design."
        )
