"""Generated by tools/generate_rule_python.py — classification: HIGH_REQUIRED_ATTRIBUTE"""

import pytest
from usdm4.rules.library.rule_ddf00037 import RuleDDF00037
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00037:
    def test_metadata(self):
        rule = RuleDDF00037()
        assert rule._rule == "DDF00037"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "At least one scheduled activity instance within a timeline must point to a timeline exit."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
