"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

import pytest
from usdm4.rules.library.rule_ddf00091 import RuleDDF00091
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00091:
    def test_metadata(self):
        rule = RuleDDF00091()
        assert rule._rule == "DDF00091"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "When a condition applies to a procedure, activity, biomedical concept, biomedical concept category, or biomedical concept surrogate then an instance must be available in the corresponding class with the specified id."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00091()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
