"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00157 import RuleDDF00157
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00157:
    def test_metadata(self):
        rule = RuleDDF00157()
        assert rule._rule == "DDF00157"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "An encounter's environmental settings must be specified according to the extensible Environmental Setting (C127262) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
