"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00044 import RuleDDF00044
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00044:
    def test_metadata(self):
        rule = RuleDDF00044()
        assert rule._rule == "DDF00044"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "The target for a condition must not be equal to its parent."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
