"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

from usdm4.rules.library.rule_ddf00216 import RuleDDF00216
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00216:
    def test_metadata(self):
        rule = RuleDDF00216()
        assert rule._rule == "DDF00216"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A study design's intervention model must be specified according to the extensible Intervention Model Response (C99076) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )
