"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00194 import RuleDDF00194
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00194:
    def test_metadata(self):
        rule = RuleDDF00194()
        assert rule._rule == "DDF00194"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "At least one attribute must be specified for an address."
        )
