"""Generated by tools/generate_rule_python.py — classification: STUB (hand-authored)"""

import pytest
from usdm4.rules.library.rule_ddf00075 import RuleDDF00075
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00075:
    def test_metadata(self):
        rule = RuleDDF00075()
        assert rule._rule == "DDF00075"
        assert rule._level == RuleTemplate.WARNING
        assert rule._rule_text == 'An activity is expected to refer to at least one procedure, biomedical concept, biomedical concept category or biomedical concept surrogate.'

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
