"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00026 import RuleDDF00026
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00026:
    def test_metadata(self):
        rule = RuleDDF00026()
        assert rule._rule == "DDF00026"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == 'A scheduled activity instance must not point (via the "timeline" relationship) to the timeline in which it is specified.'

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00026()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
