"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00230 import RuleDDF00230
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00230:
    def test_metadata(self):
        rule = RuleDDF00230()
        assert rule._rule == "DDF00230"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A study design's study type must be specified using the Study Type Response (C99077) SDTM codelist."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
