"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00170 import RuleDDF00170
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00170:
    def test_metadata(self):
        rule = RuleDDF00170()
        assert rule._rule == "DDF00170"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "All abbreviations defined for a study version must be unique."
        )
