"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00229 import RuleDDF00229
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00229:
    def test_metadata(self):
        rule = RuleDDF00229()
        assert rule._rule == "DDF00229"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A study design's study phase must be specified according to the extensible Trial Phase Response (C66737) SDTM codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00229()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
