"""Generated by tools/generate_rule_python.py — classification: HAS_IMPLEMENTATION"""

import pytest
from usdm4.rules.library.rule_ddf00142 import RuleDDF00142
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00142:
    def test_metadata(self):
        rule = RuleDDF00142()
        assert rule._rule == "DDF00142"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "A governance date type must be specified according to the extensible governance date type (C207413) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
        )

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
