"""Generated by tools/generate_rule_python.py — classification: HIGH_FORMAT"""

import pytest
from usdm4.rules.library.rule_ddf00060 import RuleDDF00060
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00060:
    def test_metadata(self):
        rule = RuleDDF00060()
        assert rule._rule == "DDF00060"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "The value for each timing must be a non-negative duration specified in ISO 8601 format."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
