"""Generated by tools/generate_rule_python.py — classification: HIGH_CT_MEMBER"""

import pytest
from usdm4.rules.library.rule_ddf00169 import RuleDDF00169
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00169:
    def test_metadata(self):
        rule = RuleDDF00169()
        assert rule._rule == "DDF00169"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "A study definition document version's status must be specified using the status Value Set Terminology (C188723) DDF codelist."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
