"""Generated by tools/generate_rule_python.py — classification: MED_TEXT (hand-authored)"""

from usdm4.rules.library.rule_ddf00236 import RuleDDF00236
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00236:
    def test_metadata(self):
        rule = RuleDDF00236()
        assert rule._rule == "DDF00236"
        assert rule._level == RuleTemplate.WARNING
        assert (
            rule._rule_text
            == "If a synonym is specified then it is not expected to be equal to the label of the biomedical concept (case insensitive)."
        )
