"""Generated by tools/generate_rule_python.py — classification: HIGH_FORMAT"""

import pytest
from usdm4.rules.library.rule_ddf00062 import RuleDDF00062
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00062:
    def test_metadata(self):
        rule = RuleDDF00062()
        assert rule._rule == "DDF00062"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "When specified, the upper limit of a timing window must be a non-negative duration in ISO 8601 format."

    @pytest.mark.skip(reason="TODO: craft positive fixture (valid USDM, rule accepts)")
    def test_valid_data_passes(self):
        pass

    @pytest.mark.skip(reason="TODO: craft negative fixture (invalid USDM, rule flags)")
    def test_invalid_data_fails(self):
        pass
