"""Generated by tools/generate_rule_python.py — classification: LOW_CUSTOM"""

import pytest
from usdm4.rules.library.rule_ddf00124 import RuleDDF00124
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00124:
    def test_metadata(self):
        rule = RuleDDF00124()
        assert rule._rule == "DDF00124"
        assert rule._level == RuleTemplate.ERROR
        assert rule._rule_text == "Referenced items in a parameter map must be available elsewhere in the data model."

    def test_not_implemented(self):
        """Lock-in: fails the moment the rule gains a real validate() body."""
        rule = RuleDDF00124()
        with pytest.raises(NotImplementedError):
            rule.validate({"data": None, "ct": None})
