"""Generated by tools/generate_rule_python.py — classification: MED_TEXT"""

from usdm4.rules.library.rule_ddf00020 import RuleDDF00020
from usdm4.rules.rule_template import RuleTemplate


class TestRuleDDF00020:
    def test_metadata(self):
        rule = RuleDDF00020()
        assert rule._rule == "DDF00020"
        assert rule._level == RuleTemplate.ERROR
        assert (
            rule._rule_text
            == "If the reason for a study amendment is 'Other' then this must be specified (attribute reasonOther must be completed), and vice versa."
        )
