import json
from usdm4.minimum.minimum import Minimum
from src.usdm4.__version__ import __package_version__


def test_init():
    instance = Minimum.minimum("Test Study", "SPONSOR-1234", "1.0.0")
    instance.study.id = "FAKE-UUID"  # UUID is dynamic
    assert json.loads(instance.to_json()) == {
        "study": {
            "description": "Test Study",
            "documentedBy": [
                {
                    "description": "The entire protocol document",
                    "id": "StudyDefinitionDocument_1",
                    "extensionAttributes": [],
                    "instanceType": "StudyDefinitionDocument",
                    "label": "Protocol Document",
                    "language": {
                        "code": "en",
                        "codeSystem": "ISO 639-1",
                        "codeSystemVersion": "2007",
                        "decode": "English",
                        "id": "Code_1",
                        "extensionAttributes": [],
                        "instanceType": "Code",
                    },
                    "name": "PROTOCOL DOCUMENT",
                    "notes": [],
                    "templateName": "Sponsor",
                    "type": {
                        "code": "C70817",
                        "codeSystem": "cdisc.org",
                        "codeSystemVersion": "2023-12-15",
                        "decode": "Protocol",
                        "id": "Code_5",
                        "extensionAttributes": [],
                        "instanceType": "Code",
                    },
                    "versions": [
                        {
                            "childIds": [],
                            "contents": [],
                            "dateValues": [
                                {
                                    "dateValue": "2006-06-01",
                                    "description": "Design approval date",
                                    "geographicScopes": [
                                        {
                                            "code": None,
                                            "id": "GeographicScope_1",
                                            "extensionAttributes": [],
                                            "instanceType": "GeographicScope",
                                            "type": {
                                                "code": "C68846",
                                                "codeSystem": "cdisc.org",
                                                "codeSystemVersion": "2023-12-15",
                                                "decode": "Global",
                                                "id": "Code_6",
                                                "extensionAttributes": [],
                                                "instanceType": "Code",
                                            },
                                        },
                                    ],
                                    "id": "GovernanceDate_1",
                                    "extensionAttributes": [],
                                    "instanceType": "GovernanceDate",
                                    "label": "Design Approval",
                                    "name": "D_APPROVE",
                                    "type": {
                                        "code": "C132352",
                                        "codeSystem": "cdisc.org",
                                        "codeSystemVersion": "2023-12-15",
                                        "decode": "Sponsor Approval Date",
                                        "id": "Code_7",
                                        "extensionAttributes": [],
                                        "instanceType": "Code",
                                    },
                                },
                            ],
                            "id": "StudyDefinitionDocumentVersion_1",
                            "extensionAttributes": [],
                            "instanceType": "StudyDefinitionDocumentVersion",
                            "notes": [],
                            "status": {
                                "code": "C25425",
                                "codeSystem": "cdisc.org",
                                "codeSystemVersion": "2023-12-15",
                                "decode": "Approved",
                                "id": "Code_4",
                                "extensionAttributes": [],
                                "instanceType": "Code",
                            },
                            "version": "1",
                        },
                    ],
                },
            ],
            "id": "FAKE-UUID",
            "instanceType": "Study",
            "label": "Test Study",
            "name": "Study",
            "versions": [
                {
                    "bcCategories": [],
                    "bcSurrogates": [],
                    "biomedicalConcepts": [],
                    "conditions": [],
                    "abbreviations": [],
                    "administrableProducts": [],
                    "amendments": [],
                    "businessTherapeuticAreas": [],
                    "dictionaries": [],
                    "documentVersionIds": [],
                    "eligibilityCriterionItems": [],
                    "extensionAttributes": [],
                    "productOrganizationRoles": [],
                    "studyInterventions": [],
                    "medicalDevices": [],
                    "dateValues": [
                        {
                            "dateValue": "2006-06-01",
                            "description": "Design approval date",
                            "geographicScopes": [
                                {
                                    "code": None,
                                    "id": "GeographicScope_1",
                                    "extensionAttributes": [],
                                    "instanceType": "GeographicScope",
                                    "type": {
                                        "code": "C68846",
                                        "codeSystem": "cdisc.org",
                                        "codeSystemVersion": "2023-12-15",
                                        "decode": "Global",
                                        "id": "Code_6",
                                        "extensionAttributes": [],
                                        "instanceType": "Code",
                                    },
                                },
                            ],
                            "id": "GovernanceDate_1",
                            "extensionAttributes": [],
                            "instanceType": "GovernanceDate",
                            "label": "Design Approval",
                            "name": "D_APPROVE",
                            "type": {
                                "code": "C132352",
                                "codeSystem": "cdisc.org",
                                "codeSystemVersion": "2023-12-15",
                                "decode": "Sponsor Approval Date",
                                "id": "Code_7",
                                "extensionAttributes": [],
                                "instanceType": "Code",
                            },
                        },
                    ],
                    "documentVersionIds": [],
                    "id": "StudyVersion_1",
                    "extensionAttributes": [],
                    "instanceType": "StudyVersion",
                    "narrativeContentItems": [],
                    "notes": [],
                    "organizations": [
                        {
                            "id": "Organization_1",
                            "identifier": "To be provided",
                            "identifierScheme": "To be provided",
                            "extensionAttributes": [],
                            "instanceType": "Organization",
                            "label": None,
                            "legalAddress": None,
                            "managedSites": [],
                            "name": "Sponsor",
                            "type": {
                                "code": "C70793",
                                "codeSystem": "cdisc.org",
                                "codeSystemVersion": "2023-12-15",
                                "decode": "Clinical Study Sponsor",
                                "id": "Code_3",
                                "extensionAttributes": [],
                                "instanceType": "Code",
                            },
                        },
                    ],
                    "rationale": "To be provided",
                    "referenceIdentifiers": [],
                    "roles": [],
                    "studyDesigns": [],
                    "studyIdentifiers": [
                        {
                            "id": "StudyIdentifier_1",
                            "extensionAttributes": [],
                            "instanceType": "StudyIdentifier",
                            "scopeId": "Organization_1",
                            "text": "SPONSOR-1234",
                        },
                    ],
                    "titles": [
                        {
                            "id": "StudyTitle_1",
                            "extensionAttributes": [],
                            "instanceType": "StudyTitle",
                            "text": "Test Study",
                            "type": {
                                "code": "C207616",
                                "codeSystem": "cdisc.org",
                                "codeSystemVersion": "2023-12-15",
                                "decode": "Official Study Title",
                                "id": "Code_2",
                                "extensionAttributes": [],
                                "instanceType": "Code",
                            },
                        },
                    ],
                    "versionIdentifier": "1",
                },
            ],
        },
        "systemName": "Python USDM4 Package",
        "systemVersion": __package_version__,
        "usdmVersion": "3.6.0",
    }
